# Generated by Django 5.1.6 on 2025-03-16 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "***REMOVED***",
            "0003_alter_item_care_instructions_alter_item_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
