# Generated by Django 5.1.6 on 2025-03-16 22:30

from django.db import migrations
from uuid import uuid4

def populate_uuid(apps, schema_editor):
    Item = apps.get_model('***REMOVED***', 'Item')
    # Populate every item with a new unique uuid
    for item in Item.objects.all():
        item.uuid = uuid4()
        item.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ("***REMOVED***", "0004_item_uuid"),
    ]

    operations = [
        migrations.RunPython(populate_uuid),

    ]
